- name: Ensure Docker is installed
  apt:
    name: docker-ce
    state: present

- name: Pull Nginx Docker image
  docker_image:
    name: "{{ nginx_docker_image }}"
    source: pull

- name: Copy Nginx configuration (if required)
  copy:
    src: "./../files/nginx.conf"
    dest: "/home/yugarinn/nginx.conf"

- name: Create Nginx container
  docker_container:
    name: nginx
    image: "{{ nginx_docker_image }}"
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - "/home/yugarinn/projects/barelyzen.me/build:/usr/share/nginx/barelyzen.me:ro"
      - "/home/yugarinn/nginx.conf:/etc/nginx/nginx.conf:ro"
