- name: Install and refresh core snap
  ansible.builtin.shell:
    cmd: "snap install core; snap refresh core"

- name: Install certbot with snap
  ansible.builtin.shell:
    cmd: "snap install --classic certbot"

- name: Install certbot Nginx plugin with snap
  ansible.builtin.shell:
    cmd: "snap install --classic certbot-nginx-unit"

- name: Create symlink for certbot
  ansible.builtin.shell:
    cmd: "ln -s /snap/bin/certbot /usr/bin/certbot"
  args:
    creates: "/usr/bin/certbot"

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Ensure certificates directory exists
  ansible.builtin.file:
    path: /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy HTTP Nginx configuration
  ansible.builtin.copy:
    src: "../files/nginx-http.conf"
    dest: "/etc/nginx/nginx.conf"

- name: Ensure Nginx is enabled and running
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true

- name: Allow HTTP on port 80
  ansible.builtin.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow HTTPS on port 443
  ansible.builtin.ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Obtain Let's Encrypt certificate
  ansible.builtin.shell:
    cmd: "certbot certonly --nginx --non-interactive --agree-tos --email yugarinn@proton.me -d barelyzen.me -d www.barelyzen.me"
  args:
    creates: "/etc/letsencrypt/live/barelyzen.me/fullchain.pem"

- name: Copy HTTPS Nginx configuration
  ansible.builtin.copy:
    src: "../files/nginx-https.conf"
    dest: "/etc/nginx/nginx.conf"
  notify: reload nginx
